---
dependencies: []

galaxy_info:
  author: victorock
  description: Google Compute Engine
  license: "license (BSD, MIT)"
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
      - 6
      - 7
    - name: Fedora
      versions:
      - all
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - all
  galaxy_tags:
    - cloud
    - google
