
- name: "Deploy AWX"
  hosts: awx
  gather_facts: true
  become: true

  tasks:
    - name: "victorock.linux"
      include_role:
        name: victorock.linux
        tasks_from: run

    - name: "geerlingguy.awx"
      include_role:
        name: geerlingguy.awx
