cloud_compute:
  instance:
    gitlab-000:
      name: gitlab-000
      size: n1-standard-1
      image: centos-7
      credential:
        username: jdacosta
        key: gitlab
      network:
        subnet: devops
        public: yes
      tags:
        - gitlab
