---
- name: Toolbox Cloud Setup
  hosts: all
  gather_facts: True
  become: yes

  vars_files:
    - vars/main.yml

  roles:
    - { role: victorock.aws-security }
    - { role: victorock.aws-cloud }
