---
- name: Toolbox Cloud Setup
  hosts: localhost
  gather_facts: False
  become: False

  vars_files:
    - vars/main.yml

  roles:
    - { role: victorock.aws-security }
    - { role: victorock.aws-cloud }
