---
- name: Create IPA-Server instance in AWS
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    ec2_region: eu-central-1

  tasks:
    - name: "AWS Security"
      include_role:
        name: victorock.aws-security
      vars:
        ec2_security_group_name: freeipa
        ec2_security_group_source: 0.0.0.0/0
        ec2_security_group_ports:
          - 22
          - 80
          - 443

    - name: "AWS Cloud"
      include_role:
        name: victorock.aws-cloud
      vars:
        ec2_cloud_instances: 1
        ec2_cloud_instance_os: CentOS Linux 7 x86_64*
        ec2_cloud_instance_type: t2.medium
        ec2_cloud_instance_boot_disk_volume_size: 60
        ec2_cloud_instance_boot_disk_delete_on_termination: yes
        ec2_cloud_instance_instance_tags:
          Name: freeipa
          Class: management
          Version: 1.0
          Environment: dev
