---
- name: "Setup IPA-Server"
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: "Linux Baseline with Security"
      include_role:
        name: victorock.linux
      vars:
        common_package_update: yes
        rhel7cis_named_server: yes
        rhel7cis_bind: yes
        rhel7cis_host_allow:
          - "0.0.0.0/0"

    - name: "IPA-Server"
      include_role:
        name: victorock.freeipa-server
      vars:
        freeipa_domain: "victorock.local"
        freeipa_hostname: "ipa.victorock.local"
