nodejs_version: "6.x"
pip_install_packages:
  - name: docker-py
awx_repo: https://github.com/ansible/awx.git
awx_repo_dir: "/opt/awx"
awx_version: devel
awx_keep_updated: yes
awx_run_install_playbook: yes
