libvirt_network:
  subnet:
    mgmt-devops-victorock-io:
      name: mgmt-devops-victorock-io
      type: nat
      cidr: "{{ cloud_provider.cidr | ipsubnet(24, 0) }}"
    internet-devops-victorock-io:
      name: internet-devops-victorock-io
      type: route
      cidr: "{{ cloud_provider.cidr | ipsubnet(24, 1) }}"
