- name: "Deploy: Ansible Tower Config"
  hosts: ansible-tower
  gather_facts: yes
  become: yes

  tasks:
    - block:
        - name: "Copy Vault to Server"
          copy:
            src: "vault"
            dest: "~/.ansible/"

        - name: "victorock.ansible-tower-config"
          include_role:
            name: "victorock.ansible-tower-config"

      rescue:
        - name: "Clean Vault in Server"
          file:
            path: "~/.ansible/vault"
            state: absent
