- name: "Deploy: Ansible Tower Config"
  hosts: tower
  gather_facts: yes
  become: yes

  vars:
    autorun: true


  roles:
    - role: "victorock.download"
      download: "gs"
      download_user: "{{ lookup('ENV', 'GS_ACCESS_KEY_ID') }}"
      download_pass: "{{ lookup('ENV', 'GS_SECRET_ACCESS_KEY') }}"
      download_file: "tower_license.txt"
      download_from: "/input/{{ download_file }}"
      download_from_bucket: "darkbulb-image-store"
      download_from_region: "europe-west1"
      download_to: "~/.ansible/tmp/{{ download_file }}"

    - role: "victorock.linux"
    - role: "victorock.tower"
