- name: "Deploy gitlab"
  hosts: gitlab
  become: true
  gather_facts: yes

  tasks:
    - name: "victorock.linux"
      include_role:
        name: victorock.linux
        tasks_from: run

    - name: "geerlingguy.gitlab"
      include_role:
        name: geerlingguy.gitlab
