- name: "Deploy gitlab"
  hosts: vmware_tag_application_gitlab
  become: true

  tasks:
    - name: "victorock.linux"
      include_role:
        name: victorock.linux
        tasks_from: run

    - name: "geerlingguy.gitlab"
      include_role:
        name: geerlingguy.gitlab
