---
sudo: required

services:
  - docker

env:
  - distribution: centos
    version: 7
  - distribution: fedora
    version: 27
  - distribution: fedora
    version: 26
  - distribution: fedora
    version: 25
  - distribution: fedora
    version: 24
  - distribution: ubuntu
    version: xenial
  - distribution: ubuntu
    version: trusty
  - distribution: debian
    version: stretch
  - distribution: debian
    version: jessie

before_install:
  - 'sudo docker pull ansible/container-conductor-${distribution}-${version}:0.9.3rc0'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/victorock.gce_config:ro ansible/container-conductor-${distribution}-${version}:0.9.3rc0 > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/victorock.gce_config/tests/test.yml --syntax-check'
  - 'sudo docker rm -f "$(cat ${container_id})"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
