- name: "Deploy FreeIPA"
  hosts: freeipa
  gather_facts: true
  become: true

  tasks:
    - name: "victorock.linux"
      include_role:
        name: victorock.linux
        tasks_from: run

    - name: "victorock.ipaserver"
      include_role:
        name: victorock.ipaserver
        tasks_from: run
