- name: "cloud_network: Sanity checks"
  import_tasks: "network/sanity.yml"

- name: "cloud_network: Process element [ public ]"
  include_tasks: "network/public.yml"
  vars:
    public: "{{ public_dict.value }}"
  with_dict: "{{ cloud_network.public }}"
  loop_control:
    loop_var: public_dict
    label: "{{ public_dict.key }}"
  when: cloud_network.public is defined
