- name: "cloud_network: Sanity checks"
  import_tasks: "network/sanity.yml"

- name: "cloud_network: Process element [ subnet ]"
  include_tasks: "network/subnet.yml"
  vars:
    cloud_network_subnet: "{{ cloud_network_subnet_dict.value }}"
  with_dict: "{{ cloud_network.subnet }}"
  loop_control:
    loop_var: cloud_network_subnet_dict
    label: "{{ cloud_network_subnet_dict.key }}"
  when: cloud_network.subnet is mapping
