---
- name: "Provision Instances"
  hosts: gce
  connection: local
  gather_facts: false
  become: false

  tasks:
    - name: "victorock.gce_config"
      include_role:
        name: victorock.gce_config
        tasks_from: run
