---
- name: "Deploy GNS3"
  hosts: gns3
  become: true
  gather_facts: true

  vars:
    autorun: yes

  roles:
    - role: victorock.linux
    - role: victorock.cockpit
    - role: victorock.libvirt
    - role: victorock.gns3_server

  tasks:
    - name: "victorock.download"
      become_user: "gns3"
      include_role:
        name: victorock.download
      vars:
        download_from: "/input/{{ download_file }}"
        download_to: "/opt/gns3/images/{{ download_file }}"
      loop: "{{ download_files }}"
      loop_control:
        loop_var: download_file
