---
- name: "Deploy GNS3"
  hosts: gns3
  become: true
  gather_facts: true

  vars:
    autorun: yes

  roles:
    - role: victorock.linux
    - role: victorock.cockpit
    - role: victorock.libvirt
    - role: victorock.gns3_server
    - role: victorock.download
      become_user: "gns3"
      download: "gs"
      download_file: "nxosv-final.7.0.3.I7.3.qcow2"
      download_user: "{{ lookup('ENV', 'GS_ACCESS_KEY_ID') }}"
      download_pass: "{{ lookup('ENV', 'GS_SECRET_ACCESS_KEY') }}"
      download_from: "/input/{{ download_file }}"
      download_from_bucket: "darkbulb-image-store"
      download_from_region: "europe-west1"
      download_to: "/opt/gns3/images/{{ download_file }}"
    - role: victorock.download
      become_user: "gns3"
      download: "gs"
      download_file: "OVMF-20160813.fd"
      download_user: "{{ lookup('ENV', 'GS_ACCESS_KEY_ID') }}"
      download_pass: "{{ lookup('ENV', 'GS_SECRET_ACCESS_KEY') }}"
      download_from: "/input/{{ download_file }}"
      download_from_bucket: "darkbulb-image-store"
      download_from_region: "europe-west1"
      download_to: "/opt/gns3/images/{{ download_file }}"
    - role: victorock.download
      become_user: "gns3"
      download: "gs"
      download_file: "vEOS-4.18.1F.qcow2"
      download_user: "{{ lookup('ENV', 'GS_ACCESS_KEY_ID') }}"
      download_pass: "{{ lookup('ENV', 'GS_SECRET_ACCESS_KEY') }}"
      download_from: "/input/{{ download_file }}"
      download_from_bucket: "darkbulb-image-store"
      download_from_region: "europe-west1"
      download_to: "/opt/gns3/images/{{ download_file }}"
    - role: victorock.download
      become_user: "gns3"
      download: "gs"
      download_file: "vios_l2-adventerprisek9-m.03.2017.qcow2"
      download_user: "{{ lookup('ENV', 'GS_ACCESS_KEY_ID') }}"
      download_pass: "{{ lookup('ENV', 'GS_SECRET_ACCESS_KEY') }}"
      download_from: "/input/{{ download_file }}"
      download_from_bucket: "darkbulb-image-store"
      download_from_region: "europe-west1"
      download_to: "/opt/gns3/images/{{ download_file }}"
