cloud_network:
  firewall:
    freeipa:
      name: freeipa
      subnet: devops
      rules:
        - name: "freeipa-ssh-all"
          src_cidr: 0.0.0.0/0
          dst_port: 22
          proto: tcp

        - name: "freeipa-http-all"
          src_cidr: 0.0.0.0/0
          dst_port: 80
          proto: tcp

        - name: "freeipa-https-all"
          subnet: jenkins
          src_cidr: 0.0.0.0/0
          dst_port: 443
          proto: tcp

        - name: "freeipa-icmp-all"
          subnet: jenkins
          src_cidr: 0.0.0.0/0
          proto: icmp
