- name: "network.dns: Ensure state of Managed Zone [ {{ cloud_network_dns.name }} ]"
  gcp_dns_managed_zone:
    project: "{{ cloud_network.project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"
    name: "{{ cloud_network_dns.name }}"
    dns_name: "{{ cloud_network_dns.zone }}."
    description: "{{ cloud_network_dns.description | default('Managed by Ansible') }}"
    scopes:
        - https://www.googleapis.com/auth/ndev.clouddns.readwrite
    state: "{{ cloud_network_dns.state | default(omit) }}"

- name: "network.dns: Ensure state of Zone [ {{ cloud_network_dns.name }} ]"
  gcdns_zone:
    project_id: "{{ cloud_network.project }}"
    zone: "{{ cloud_network_dns.zone }}"
    state: "{{ cloud_network_dns.state | default(omit) }}"

- name: "network_dns: Ensure Zone's record state for [ {{ cloud_network_dns.record }} ]"
  gcdns_record:
    project_id: "{{ cloud_network.project }}"
    zone: "{{ cloud_network_dns.zone }}"
    record: "{{ cloud_network_dns.record }}"
    value: "{{ cloud_network_dns.value | default(cloud_network_facts.public[cloud_network_dns.public].address) }}"
    type: "{{ cloud_network_dns.type | default('A') }}"
    ttl: "{{ cloud_network_dns.ttl | default('60') }}"
    state: "{{ cloud_network_dns.state | default(omit) }}"
