- name: "cloud_compute.instance: Ensure instance's state as present [ {{ instance.name }} ]"
  gce:
    name: "{{ instance.name }}"
    zone: "{{ cloud_compute.zone }}"
    machine_type: "{{ instance.size | default(omit) }}"
    disk_size: "{{ instance.boot.size | default(omit) }}"
    persistent_boot_disk: "{{ instance.boot.persistent | default(omit) }}"
    image: "{{ instance.image | default(omit) }}"
    image_family: "{{ instance.image_family | default(omit) }}"
    external_ip: "{{ instance.network.public | default(omit) }}"
    network: "{{ instance.network.subnet }}"
    state: "present"

- name: "cloud_compute.instance: Ensure instance's state as started for [ {{ instance.name }} ]"
  gce:
    name: "{{ instance.name }}"
    zone: "{{ cloud_compute.zone }}"
    machine_type: "{{ instance.size | default(omit) }}"
    disk_size: "{{ instance.boot.size | default(omit) }}"
    persistent_boot_disk: "{{ instance.boot.persistent | default(omit) }}"
    image: "{{ instance.image | default(omit) }}"
    image_family: "{{ instance.image_family | default(omit) }}"
    external_ip: "{{ instance.network.public | default(omit) }}"
    network: "{{ instance.network.subnet }}"
    state: "started"

- name: "cloud_compute.instance: Gather Instance facts for [ {{ instance.name }} ]"
  gce:
    name: "{{ instance.name }}"
    zone: "{{ cloud_compute.zone }}"
    machine_type: "{{ instance.size | default(omit) }}"
    disk_size: "{{ instance.boot.size | default(omit) }}"
    persistent_boot_disk: "{{ instance.boot.persistent | default(omit) }}"
    image: "{{ instance.image | default(omit) }}"
    image_family: "{{ instance.image_family | default(omit) }}"
    external_ip: "{{ instance.network.public | default(omit) }}"
    network: "{{ instance.network.subnet }}"
    state: "present"
  register: cloud_compute_facts_instance

- name: "cloud_compute.instance: Set cloud_compute_facts.instance[ {{ instance.name }} ]"
  set_fact:
    cloud_compute_facts: "{{ cloud_compute_facts | combine({ 'instance': { instance.name: cloud_compute_facts_instance.instance_data[0] } }) }}"

- name: "cloud_compute.instance: Ensure tags for instance [ {{ instance.name }} ]"
  gce_tag:
    instance_name: "{{ instance.name }}"
    zone: "{{ cloud_compute.zone }}"
    tags: "{{ instance.tags }}"
    state: "{{ instance.state | default(omit) }}"
  when: instance.tags is sequence

- name: "cloud_compute.instance: Ensure inventory for instance [ {{ instance.name }} ]"
  add_host:
    name: "{{ instance.name }}"
    groups: "{{ instance.tags | default(omit) }}"
    ansible_user: "{{ instance.credential.username }}"
    ansible_host: "{{ cloud_compute_facts.instance[instance.name].public_ip }}"
    ansible_ssh_host: "{{ cloud_compute_facts.instance[instance.name].public_ip }}"
    instance_facts: "{{ cloud_compute_facts.instance[instance.name] }}"

- name: "cloud_compute.instance: Wait for reachability of instance [ {{ instance.name }} ]"
  delegate_to: "{{ instance.name }}"
  wait_for_connection:
    timeout: 900

- name: "cloud_compute.instance: Gather facts from instance [ {{ instance.name }} ]"
  delegate_to: "{{ instance.name }}"
  setup:
