- src: https://github.com/victorock/ansible-role-awx.git
  scm: git
  version: victorock-galaxy-dependencies
  name: geerlingguy.awx

- name: victorock.security

- src: https://github.com/victorock/ansible-role-linux.git
  scm: git
  version: dev
  name: victorock.linux

- src: https://github.com/victorock/ansible-role-gce-config.git
  scm: git
  version: dev
  name: victorock.gce_config
